# Adicionando suporte para rodar o analysis como um serviço separado no Docker
FROM python:3.9-slim

# Diretório de trabalho
WORKDIR /app

# Copiar os arquivos necessários
COPY ./tests/analysis.py ./
COPY ./artifacts /app/artifacts
COPY ./ml/requirements.txt ./requirements.txt

# Instalar dependências
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install matplotlib seaborn scikit-learn

# Criar a pasta analysis dentro de artifacts
RUN mkdir -p /app/artifacts/analysis

# Comando para rodar o script de análise
CMD ["python", "analysis.py"]