FROM tensorflow/tensorflow:2.13.0-gpu

WORKDIR /app

COPY ./requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . /app

EXPOSE 8000

CMD ["flask", "run", "--host=0.0.0.0", "--port=8000"]